version: '3.8'

services:
  # Main FastAPI application
  health-monitoring-api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/health_monitoring.db
      - LOG_LEVEL=INFO
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - health-network

  # Redis for caching and simple queuing
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - health-network

  # NGINX reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - health-monitoring-api
    restart: unless-stopped
    networks:
      - health-network

  # Simple monitoring dashboard (Streamlit)
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend
    environment:
      - DATABASE_URL=sqlite:///./data/health_monitoring.db
    depends_on:
      - health-monitoring-api
    restart: unless-stopped
    networks:
      - health-network

volumes:
  redis_data:

networks:
  health-network:
    driver: bridge
